#!/usr/bin/env bash
# Wipe ISE build artifacts. Keeps source files (.v, .vhd, .psm, .ucf, .xst, .prj, .sh).
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

# Generated by KCPSM6 / our rename step
rm -f recorder_ui.v recorder_ui.fmt recorder_ui.hex recorder_ui.log program.v
rm -f KCPSM6_session_log.txt

# Generated by XST / NGDBuild / MAP / PAR / BitGen
rm -rf xst _ngo _xmsgs xlnx_auto_0_xdb
rm -f audio_recorder.{ngc,ngd,bld,bgn,bit,drc,lso,ncd,pad,par,pcf,prj.bak,ptwx}
rm -f audio_recorder.{stx,syr,twr,twx,unroutes,ut,xpi,xrpt,xst}.tmp 2>/dev/null || true
rm -f audio_recorder.{syr,bld,bgn,drc,lso,pad,par,pcf,ptwx,stx,twr,twx,unroutes,ut,xpi,xst}
rm -f audio_recorder_map.{map,mrp,ncd,ngm,xrpt}
rm -f audio_recorder_summary.{html,xml} audio_recorder_usage.xml
rm -f audio_recorder_envsettings.html audio_recorder_bitgen.xwbt
rm -f audio_recorder_ngdbuild.xrpt audio_recorder_par.{xrpt,unroutes}
rm -f audio_recorder_xst.xrpt audio_recorder_pad.{csv,txt}
rm -f par_usage_statistics.html usage_statistics_webtalk.html webtalk*.log webtalk_pn.xml
rm -f netlist.lst impact_batch.cmd

echo "Cleaned."
